// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfjqzjdypwclysivtxft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5manF6amR5cHdjbHlzaXZ0eGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDE3MjIsImV4cCI6MjA2NDk3NzcyMn0.DWXarO8AT9E9f1JOJyjP7sMbpHoDa3-hSTezFf_m7rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);